In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [2]:
DATA_PATH = "/content/drive/MyDrive/EmployeeAttrition/Employee_Dataset.csv"

In [3]:
import pandas as pd

data = pd.read_csv(DATA_PATH)

In [4]:
import numpy as np

In [5]:
age_array = np.array(data["Age"])

print(age_array)

[41 49 37 ... 27 49 34]


In [6]:
print("Shape:", age_array.shape)
print("Dimensions:", age_array.ndim)
print("Number of values:", age_array.size)
print("Data type:", age_array.dtype)

Shape: (1470,)
Dimensions: 1
Number of values: 1470
Data type: int64


In [7]:
print(age_array[0])
print(age_array[1])
print(age_array[2])

41
49
37


In [8]:
print("Average age:", np.mean(age_array))
print("Maximum age:", np.max(age_array))
print("Minimum age:", np.min(age_array))
print("Median age:", np.median(age_array))
print("Standard deviation:", np.std(age_array))

Average age: 36.923809523809524
Maximum age: 60
Minimum age: 18
Median age: 36.0
Standard deviation: 9.132265690615387


In [9]:
print(age_array[0:5])

[41 49 37 33 27]


In [10]:
print(age_array[:10])

[41 49 37 33 27 32 59 30 38 36]


In [11]:
age_plus_one = age_array + 1

print(age_plus_one[:10])

[42 50 38 34 28 33 60 31 39 37]


In [12]:
older_employees = age_array[age_array > 40]

print(older_employees)

[41 49 59 53 53 42 44 46 44 43 50 41 46 48 44 50 59 55 45 59 45 46 55 56
 51 46 51 46 54 58 44 59 50 51 54 43 56 51 58 49 43 50 41 51 45 41 41 53
 45 51 58 57 50 41 45 56 46 41 50 53 55 51 52 43 45 42 49 46 51 41 45 54
 59 52 42 59 50 43 52 41 45 45 42 42 51 46 45 55 47 50 53 42 55 44 49 42
 51 41 58 45 43 49 52 47 43 54 43 45 41 47 42 42 48 42 57 46 41 50 49 51
 55 42 43 54 43 43 56 41 52 45 52 42 60 46 42 57 50 60 47 46 54 46 42 48
 55 41 42 45 41 46 41 52 49 50 42 43 43 48 44 44 53 45 54 48 50 50 47 53
 41 60 41 50 44 47 42 43 56 53 52 45 47 55 52 54 42 52 50 47 58 42 45 42
 49 55 43 51 44 53 45 52 44 42 49 42 53 53 43 47 50 44 58 43 47 41 42 58
 49 48 41 45 52 58 53 47 45 50 41 45 47 50 46 54 48 48 41 42 50 59 55 41
 52 44 50 45 59 45 53 50 46 54 56 55 43 46 51 41 55 44 42 50 48 45 52 46
 43 49 42 41 42 42 43 56 45 44 53 46 44 41 50 46 44 46 42 60 42 54 44 54
 59 43 49 48 48 44 45 55 46 51 59 44 42 43 44 51 45 58 46 50 52 41 44 42
 55 56 41 51 58 48 51 55 56 51 41 52 43 42 52 49 54

In [13]:
print("First 10 ages:")
print(age_array[:10])

print("\nAverage age:")
print(np.mean(age_array))

print("\nEmployees older than 40:")
print(np.sum(age_array > 40))

First 10 ages:
[41 49 37 33 27 32 59 30 38 36]

Average age:
36.923809523809524

Employees older than 40:
465


In [14]:
print("Total employees:", age_array.size)
print("Average age:", np.mean(age_array))
print("Youngest employee:", np.min(age_array))
print("Oldest employee:", np.max(age_array))
print("Median age:", np.median(age_array))

Total employees: 1470
Average age: 36.923809523809524
Youngest employee: 18
Oldest employee: 60
Median age: 36.0


In [15]:
below_30 = np.sum(age_array < 30)

print("Employees below 30:", below_30)

Employees below 30: 326


In [16]:
between_30_40 = np.sum((age_array >= 30) & (age_array <= 40))

print("Employees between 30 and 40:", between_30_40)

Employees between 30 and 40: 679


In [17]:
above_40 = np.sum(age_array > 40)

print("Employees above 40:", above_40)

Employees above 40: 465


In [18]:
total_age = np.sum(age_array)

print("Total age:", total_age)

Total age: 54278


In [19]:
age_std = np.std(age_array)

print("Age standard deviation:", age_std)

Age standard deviation: 9.132265690615387
